# Generated by Django 4.1.13 on 2025-04-06 12:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="Diet",
            new_name="Analytics",
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_in",
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name="attendance",
            name="check_out",
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="attendance",
            name="present",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="bmi",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="bmr",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="calorie_difference",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="heart_rate_avg",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="heart_rate_margin",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="heart_reserve",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="intesity_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="maximum_heart_rate",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="target_bmi",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="target_calorie_intake",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="target_weight",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="tdee",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bodyindex",
            name="workout_intensity",
            field=models.CharField(default="moderate", max_length=50),
        ),
        migrations.AddField(
            model_name="equipment",
            name="last_service_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="equipment",
            name="maintainence_status",
            field=models.CharField(
                choices=[
                    ("functional", "functional"),
                    ("under maintenance", "under maintenance"),
                    ("out of order", "out of order"),
                    ("needs repair", "needs repair"),
                ],
                default="functional",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="measurement",
            name="activity_level",
            field=models.CharField(
                choices=[
                    ("sedentary", "sedentary"),
                    ("light", "light"),
                    ("moderate", "moderate"),
                    ("active", "active"),
                    ("very active", "very active"),
                ],
                default="moderate",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="chest",
            field=models.FloatField(default=0.0, help_text="Chest in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="measurement",
            name="height",
            field=models.FloatField(default=0.0, help_text="Height in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="left_biceps",
            field=models.FloatField(default=0.0, help_text="Left biceps in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="left_calf",
            field=models.FloatField(default=0.0, help_text="Left calf in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="left_thigh",
            field=models.FloatField(default=0.0, help_text="Left thigh in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="right_biceps",
            field=models.FloatField(default=0.0, help_text="Right biceps in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="right_calf",
            field=models.FloatField(default=0.0, help_text="Right calf in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="right_thigh",
            field=models.FloatField(default=0.0, help_text="Right thigh in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="target_weight",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="measurement",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="measurement",
            name="waist",
            field=models.FloatField(default=0.0, help_text="Waist in cm"),
        ),
        migrations.AddField(
            model_name="measurement",
            name="weight",
            field=models.FloatField(default=0.0, help_text="Weight in kg"),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="duration",
            field=models.IntegerField(
                choices=[
                    (1, "1 Month"),
                    (3, "3 Months"),
                    (6, "6 Months"),
                    (12, "12 Months"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="features",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="plan_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="membershipplan",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="trainer",
            name="age",
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name="trainer",
            name="contact",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="trainer",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trainer",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("other", "other")],
                default="male",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="trainer",
            name="joining_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="trainer",
            name="name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="trainer",
            name="specialization",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="gender",
            field=models.CharField(
                choices=[("male", "male"), ("female", "female"), ("other", "other")],
                default="male",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.membershipplan",
            ),
        ),
        migrations.AddField(
            model_name="userdetail",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="equipment",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.equipment",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="muscle",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="potential_calorie_burn",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="WorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.datetime.today)),
                ("duration", models.IntegerField(default=1)),
                (
                    "session",
                    models.CharField(
                        choices=[
                            ("morning", "morning"),
                            ("evening", "evening"),
                            ("both", "both"),
                        ],
                        default="morning",
                        max_length=50,
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "cash"), ("card", "card"), ("upi", "upi")],
                        default="cash",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                (
                    "membership",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.membershipplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MorningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.workoutplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EveningSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workout_plan",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.workoutplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart", models.JSONField(default=list)),
                ("duration", models.IntegerField(default=None, null=True)),
                (
                    "trainer",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.trainer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddWorkoutPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evening_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.eveningsession",
                    ),
                ),
                (
                    "morning_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.morningsession",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.workout"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AddRep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=10)),
                ("weight", models.FloatField(default=5.0)),
                (
                    "add_workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.addworkoutplan",
                    ),
                ),
            ],
        ),
    ]
