# Generated by Django 4.1.13 on 2025-04-06 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_workoutsession_rename_diet_analytics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addworkoutplan",
            name="evening_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.eveningsession",
            ),
        ),
        migrations.AlterField(
            model_name="addworkoutplan",
            name="morning_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.morningsession",
            ),
        ),
    ]
